"""empty message

Revision ID: 216b4685b1c9
Revises: 6b682bfaad57
Create Date: 2022-07-08 18:30:42.969817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216b4685b1c9'
down_revision = '6b682bfaad57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('country', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'country')
    # ### end Alembic commands ###
