"""empty message

Revision ID: 5ed8711f6698
Revises: b59a1fefbf8e
Create Date: 2022-06-15 00:07:43.897822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed8711f6698'
down_revision = 'b59a1fefbf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=60), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
